
[font]
size = 14

[font.normal]
family = "Maple Mono NF"
style = "Normal"

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

[general]
import = ["~/.config/alacritty/themes/themes/everforest_light.toml"]
